```{r managment_plot_caption}
management_plot_caption <-
  "Ternary diagram highlighting the feasible region of managment (maximum allowed thinning of 20%) and the four vertices representing potential optimal solutions to the decision problem."
```

```{r param_plot_caption}
param_plot_caption <-
  "Frequency histogram of a state and transition model parameter. Histogram shows expert elicted estimates of the probability of a section of the BIFAW transitioning from HDRG to LDRG due to Windthrow if the ecological management option is used."
```

```{r results_plot1_caption}
results_plot1_caption <-
  "The expected value of partial perfect information (EVPXI) for the top four transition probabilities on their own (top panel), the top two transition probabilities out of each state (middle panel) and the top two transition probabilities for each management option (bottom panel) compared with the expected value of perfect information (EVPI)."
```

```{r results_plot2_caption}
results_plot2_caption <-
  "Response of the expected value information to changing the constraint on the allowable proportion of the BIFAW to undergo ecological thinning (ET). The top grey line is EVPI. The three black lines are the EVPXI for the most valuable parameter associated with each action."
```