
```{r management_plot, fig.cap = management_plot_caption}
ggtern(
  data = 
    data_frame(
      `Ecological Thinning`      = c(0, 0, .2, .2),
      `Harvest/\nFirewood Removal` = c(0, 1, .8, 0),
      `No Management`            = c(1, 0, 0, .8),
      Feasible = "Feasible management",
      Vertices = "Potentially optimal solutions"
    ),
  aes(
    x = `Ecological Thinning`,
    y = `Harvest/\nFirewood Removal`,
    z = `No Management`
  )
) +
geom_polygon(aes(fill = Feasible), alpha = .5) +
geom_mask() +
geom_point(aes(col = Vertices), size = 3) +
scale_color_grey("") +
scale_fill_grey("") +
theme_bw() +
theme_showarrows() +  
theme(
  tern.axis.title      = element_blank(),
  legend.position      = 0:1,
  legend.justification = 0:1,
  legend.box.just      = "left",
  legend.key           = element_blank(),
  legend.background    = element_rect(size = 0)
)
```

```{r results_plot1, fig.cap = results_plot1_caption}
ggplot(evi) +
aes(parameters, evi, width = width, fill = evpi) +
geom_bar(stat = "identity") +
scale_y_continuous(
  "Expected Value of Information",
  labels = scales::percent
) + 
scale_fill_grey() +
ylab("") +
guides(fill = FALSE) +
facet_wrap(~type, ncol = 1, scales = "free") +
theme_bw()
```

```{r results_plot2, fig.cap = results_plot2_caption}
ggplot() +
aes(x = max_eco, y = evi) +
geom_line(
  data = evpi_df,
  size = 1.25,
  col = "grey"
) +
geom_line(
  aes(linetype = action),
  data = evpxi_df,
  size = 1.25
) +
scale_linetype_discrete(
  name = "Action",
  guide = guide_legend(keywidth = 2)
) +
scale_x_continuous(
  "Maximum allowed ecological thinning",
  labels = scales::percent
) +
scale_y_continuous("Expected Value of Information", labels = scales::percent) +
theme_bw() +
theme(legend.justification = c(0, 1), legend.position = c(0, 1))
```

