Introduction
============

Ecosystems are typically managed under uncertainty. Reducing uncertainty (through monitoring, experiments, or external research) can facilitate management decisions with greater expected benefits. On the other hand, sometimes reducing uncertainty is not warranted [@Mcdonaldmadden2010]. The decision to gather information at all, is only rational if the expected benefit when making a decision with new information outweighs the cost of learning. Determining the value of information facilitates calculating this benefit [@Raiffa1968].

Value of information (VOI) theory is a set of decision theoretic tools that have previously been applied to decision problems in economics, medicine, engineering and other domains [@Dakins1999; @Yokota2004; @Claxton2008; @Wu2013]. With the VOI toolset, a decision analyst can assess what to monitor, how much to monitor and even whether monitoring is justified at all.

Compared with other fields, such as operations research and medicine, ecology and natural resource management have been slower to adopt VOI analyses for decision making, although recently, some examples have appeared in the literature [e.g., @Polasky2001; @Moore2011; @Runge2011; @Runting2013]. Most examples have focused on evaluating VOI for models with discrete expressions of model uncertainty [e.g., @Moore2012]. Furthermore, ecological decision problem solvers have tended to focus on models of population dynamics [@Runge2011; @Canessa2015; @Johnson2014; @Maxwell2015] rather than community and/or ecosystem-level models. This is an important gap in our understanding, as much effort and resources are expended on ecosystem management.

One reason why communities and ecosystems have rarely been the focus of VOI analyses is that community or ecosystem models do not lend themselves easily to VOI analysis. Ecosystem models, such as state and transition models, exhibit complex nonlinear dynamics, have many parameters (multidimensional), and their critical uncertainties are often continuous (rather than discrete), making it difficult to calculate the VOI analytically.

An approach to dealing with multidimensional continuous uncertainty and avoid having to contend with the complex integral calculus needed to perform a VOI analytically, is to simplify the problem by representing the uncertainty with a set of discrete values. Here we introduce a case study on VOI for a complex, high-dimensional model with underlying continuous uncertainty represented by sets of discrete parameter values. For the present analysis we purposely avoid the issue of non-linear temporal dynamics and only set out to address the problems of high-dimensionality and continuous uncertainty, leaving this third potential source of complexity for another forum.

In the work that follows we briefly introduce our motivating example of Box Ironbark Forest and Woodland (BIFAW) management and revisit the state transition models of this system built by @Czembor2009. We then provide the reader with some introductory material on VOI analyses and its variants, before applying these techniques to our case study and demonstrate how some of the inherent complexities can be addressed by discretising the uncertainty and applying stepwise algorithms that negate the need for complex integral calculus.

Box Ironbark Forest and Woodland management
-------------------------------------------

The BIFAW region covers approximately 250,000ha of central Victoria, Australia. The BIFAW are plant communities that occur on low-fertility soils and in a semi-arid to temperate climate. Much of the pre-European stands of BIFAW were cleared for agriculture and gold mining. Most of the current extent is highly fragmented regrowth. These regrowth stands are typically missing key ecosystem components such as large, hollow-bearing trees and a diverse understory shrub layer. Tree species found in BIFAW include Grey Box (*Eucalyptus microcarpa*), Red Box (*E. polyanthemos*), Long Leaf Box (*E. goniocalyx*), Yellow Box (*E. melliodora*), Red Ironbark (*E. tricarpa*), Red Stringybark (*E. macrorhyncha*) and Yellow Gum (*E. leucoxylon*). The BIFAW supports important habitat for three Victorian-listed threatened taxa: Brush-tailed Phascogale (*Phascogale tapoatafa*), Powerful Owl (*Ninox strenua*) and Regent Honeyeater (*Xanthomyza phrygia*) [@Tzaros2005]. The latter is also a federally listed endangered species. Regent Honeyeaters are threatened because they rely on large trees for foraging and nesting [@Menkhorst1999].

In 1996 the state government of Victoria commissioned an investigation into an appropriate system for the protection and management of BIFAW. As a direct result, over 200,000 ha of BIFAW were gazetted as national park and other protected areas. The report recommended a program of ecological thinning be undertaken as part of an ecological management strategy to assist the development of a forest structure ultimately dominated by large diameter trees in the new parks and reserves [@ECC2001; @Pigott2009]. 'Ecological thinning' is the active reduction of stem density to improve forest health, while retaining some fallen timber to improve habitat for plants and animals [@Cunningham2009]. In 2003 the body in charge of BIFAW park management, Parks Victoria, established an ecological thinning trial. The aim of the trial was to investigate whether ecological thinning could be used to restore structural diversity of habitat types and the functioning and persistence of key communities and species populations [@Pigott2010].

### State and transition models of Box Ironbark Forest and Woodland

@Czembor2009 built a suite of simulation models of BIFAW dynamics with parameters estimated through expert elicitation using methods adapted from @Morgan1990. Their BIFAW state and transition models predict the proportions of a model landscape in four states: high-density regrowth (HDRG), low-density regrowth (LDRG), and the two states most desired by land-managers, mature high-density woodland (MHDW), and mature low-density woodland (MLDW). The models included three management options, no management/natural disturbance only (NM), a scenario of limited harvest/firewood removal (HF), and ecological thinning (ET). Briefly, the models predict state of the landscape through time by applying a transition matrix that differs according to the management action applied [see methods and @Czembor2009; and @Czembor2011 for more information].

The state and transition models of Czembor et al make the simplifying assumption that the dynamics of the system are linear with respect to the actions taken. That is, they lack interactions that make the outcome of one action depend on the application of any other action. In effect, there were separate models for each of the actions, one model that predicted the dynamics (changes in state through time) of the BIFAW when NM was applied, one model for HF and one for ET. While a more complex model that included the extra layer of dynamism and included non-linear relationships between combinations of actions and outcome may have produced more realistic results, the simplification was necessary to facilitate the expert elicitation used to parameterise the models. Further, by using these discrete parameter estimates as the inputs of the VOI analyses outlined below, we can avoid the complex calculus necessary when using continous distributions directly.

### Uncertainty in Box Ironbark Forest and Woodland models

Analyzing the variation among models which included three components of uncertainty, @Czembor2011 found that between-expert uncertainty was the greatest contributor to total model uncertainty, followed by imperfect individual expert knowledge, then system stochasticity. In the case presented here we treated the opinions of the experts as the initial state of uncertainty---the original information.

Uncertainty in state and transition model parameters can be represented by a continuous multidimensional (where the dimensions are the different model parameters) probability distribution. However, the elicitation process used by Czembor et al, yields an approximation of such a distribution in the form of multiple discrete estimates of each parameter (in this case 375 estimates per parameter) that represents the underlying continuous expression of uncertainty. With the discrete estimates of the parameter values we can summarise the continuous parameter space, in much the same way as a histogram of samples represents some underlying probability distribution.

Calculating the value of information
------------------------------------

A value of information analysis can be used to assess the benefit of reducing epistemic uncertainty before making a decision. A decision analyst cannot know, in advance, what information they will gain if they seek to learn before taking action. The expected value _of_ information (EVI) is the difference between the expected value with _new_ information (EVWNI) and the expected value with _original_ information (EVWOI). The EVI can come in a number forms depending on the form of new information. Regardless of form, all variants of EVI analyses assume decisions are being made optimally. That is, the decision analyst considers value to arise from taking actions that maximize the expected value given the original or new information. To do so, the decision analyst requires a model that can be used to predict the outcomes of possible future decisions. In calculating EVI, the analyst will use such a model to predict decision outcomes using the original or new information as their model inputs.

As noted above, value of information can take multiple forms. Here we deal with two forms: the expected value of perfect information (EVPI) and the partial expected value of perfect information (EVPXI). Where X in this case indicates the component (part) of information that will be know perfectly. Here we will briefly outline the general form of an EVI analysis in terms of EVPI and EVPXI. For a more detailed description of the derivation of EVI and its variants, see the seminal text of @Raiffa1968 and for more recent treatments see @Yokota2004 and @Williams2011.

The expected value of perfect information (EVPI) quantifies the expected performance gain if all uncertainty is resolved prior to taking action [@Raiffa1968]. The EVPI is the upper bound of expected performance improvement and can identify the amount of resources worth investing to resolve uncertainty [@Runge2011]. While EVPI provides a value for complete reduction of uncertainty, EVPXI can quantify the performance gain if uncertainty is only partially resolved [@Ades2004].

Again, the EVI is the difference between the EVWNI and the EVWOI. When the new information is perfect (i.e., the analyst's model will have all uncertainty eliminated) then it follows that:

$$ \mathrm{EVPI} = \mathrm{EVWPI} - \mathrm{EVWOI}, $$

where EVWPI is the expected value _with_ perfect information.

To calculate the expected values EVWPI and EVWOI, like any expected value, the analyst will work out the value they expect to see on average when taking the most optimal, or maximizing actions. More formally:

$$ \mathrm{EVWOI} = Max_{a}[Mean_{s}(Value)] $$

and

$$ \mathrm{EVWPI} = Mean_{s}[Max_{a}(Value)]. $$

Where $a$ indicates the actions available and $s$ indicates the initial uncertainty or the state space (the world of possible scenarios that could lead an action to generate some value). As you can see, both the equations for EVWPI and EVWOI are similar. The key difference is the order of maximization (optimizing) and averaging (taking the mean over the uncertainty). Calculating the EVPXI requires a similar yet more complicated approach. For a model with multiple parameters, to calculate the EVPXI for the $i^{th}$ parameter(s) of interest is expressed formally as:

$$ \mathrm{EVPXI_i} = \mathrm{EVWPXI_i} - \mathrm{EVWOI}, $$

where,

$$ \mathrm{EVWPXI_i} = Mean_{s_i}\{Max_{a}[Mean_{s_c}(Value)]\}. $$

Here $c$ represents the rest of the parameters in the model with uncertainty, $s$. Partial perfect information requires an additional 'averaging over' step, where value is averaged over the $c^{th}$ not-of-interest parameters, then maximization occurs, before finally averaging over the initial uncertainty of the parameter(s) of interest takes place.

Study objectives
----------------

In the following work we apply the above calculations of EVPI and EVPXI to the BIFAW model to ascertain whether and how the addition of new information may improve the outcome of their management. To find the upper bound on the value of information we calculated the expected value of perfect information (EVPI) for the BIFAW model. We then calculated the the partial value of perfect information (EVPXI) for all transition probabilities to determine which parameters have the greatest value for learning. We also analysed a set of sampling strategies that resolved the uncertainty for multiple parameters simultaneously by calculating EVPXI for two parameters of transitions out of each system state, and two parameters of transitions for each management action (see methods section for further details). Finally we tested the effect of varying a constraint on action to see what happened to the expected value of information when the options available to a manager changed.
