---
title: "The value of information for woodland management: updating a state and transition model"
author: "William K. Morris, Michael C. Runge & Peter A. Vesk"
date: "`r Sys.Date()`"
output:
  pdf_document:
    fig_caption: yes
    citation_package: natbib
    keep_tex: yes
    dev: png
header-includes:
- \linespread{2}\selectfont
- \usepackage{setspace}
- \usepackage[labelsep = none, textformat = empty]{caption}
- \usepackage[nomarkers]{endfloat}
- \AtBeginDelayedFloats{\linespread{2}}
- \usepackage{lineno}
- \linenumbers
bibliography: voiWoodland.bib
biblio-style: apalike
---

```{r analyses, child = "analyses.rmd"}
```
\newpage

```{r abstract, child = "abstract.rmd"}
```
\newpage

```{r introduction, child = "introduction.rmd"}
```
\newpage

```{r methods, child = "methods.rmd"}
```
\newpage

```{r results, child = "results.rmd"}
```
\newpage

```{r discussion, child = "discussion.rmd"}
```
\newpage

```{r acknowledgements, child = "acknowledgements.rmd"}
```
\newpage

```{r captions, child = "captions.rmd"}
```

```{r figures, child = "figures.rmd"}
```

Literature cited
================
